/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import gestion_stock.controlador.productosController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Caro
 */
public class Productos_Vista extends javax.swing.JFrame {

    productosController productosControlles = new productosController();

    public Productos_Vista() {
        initComponents();
        
        productosControlles.consultarLista(listaTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CrearButton = new javax.swing.JButton();
        BorrarButton = new javax.swing.JButton();
        ModificarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTable = new javax.swing.JTable();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel1.setText("Listado Productos");

        CrearButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        CrearButton.setForeground(new java.awt.Color(153, 255, 51));
        CrearButton.setText("Crear");
        CrearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearButtonActionPerformed(evt);
            }
        });

        BorrarButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BorrarButton.setForeground(new java.awt.Color(255, 0, 0));
        BorrarButton.setText("Borrar");
        BorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarButtonActionPerformed(evt);
            }
        });

        ModificarButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ModificarButton.setForeground(new java.awt.Color(204, 0, 204));
        ModificarButton.setText("Modificar");
        ModificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarButtonActionPerformed(evt);
            }
        });

        listaTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        listaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listaTable);

        volverButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        volverButton.setForeground(new java.awt.Color(255, 51, 204));
        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CrearButton)
                        .addGap(49, 49, 49)
                        .addComponent(BorrarButton)
                        .addGap(45, 45, 45)
                        .addComponent(ModificarButton)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(volverButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volverButton)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearButton)
                    .addComponent(BorrarButton)
                    .addComponent(ModificarButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearButtonActionPerformed

    agregar_producto_vista agregarProducto = new agregar_producto_vista();
    
    // Hacer visible la nueva ventana
    agregarProducto.setVisible(true);
    
    // Si quieres ocultar la ventana actual, puedes hacerlo con:
    this.dispose();
        
    }//GEN-LAST:event_CrearButtonActionPerformed

    private void ModificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarButtonActionPerformed
        
    // Tomo el valor de la fila que selecciona el usuario
    int filaSeleccionada = listaTable.getSelectedRow();
    
    // Verifico si el usuario ha seleccionado una fila
    if (filaSeleccionada != -1) {
        // Obtengo los datos de la fila seleccionada
        String idProducto = listaTable.getValueAt(filaSeleccionada, 0).toString();
        String nombre = listaTable.getValueAt(filaSeleccionada, 1).toString();
        String descripcion = listaTable.getValueAt(filaSeleccionada, 2).toString();
        double precio = Double.parseDouble(listaTable.getValueAt(filaSeleccionada, 3).toString());

        // Paso los datos a la vista de modificación
        Modificar_Vista modificarVista = new Modificar_Vista(idProducto, nombre, descripcion, precio);
        modificarVista.setVisible(true);
        
        // Cierro la ventana actual si es necesario
        this.dispose();
    } else {
        // Si no selecciona ninguna fila
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto para modificar");
    }
    }//GEN-LAST:event_ModificarButtonActionPerformed

    private void BorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButtonActionPerformed
        
        int filaSeleccionada = listaTable.getSelectedRow();
        
         // Verifico si el usuario ha seleccionado una fila
        if (filaSeleccionada != -1) {
            String id_producto = listaTable.getValueAt(filaSeleccionada, 0).toString();

            System.out.println("Fila "+ filaSeleccionada +" id "+ id_producto);

            productosControlles.borrarProducto(id_producto);
            /*
            try {
                productosControlles.borrarProducto(id_producto);
            } catch (ParseException ex) {
                Logger.getLogger(Productos_Vista.class.getName()).log(Level.SEVERE, null, ex);
            }*/

            //eliminar_vista eliminarVista = new eliminar_vista ();

            //eliminarVista.setVisible(true);

            //this.dispose();
        }else {
            // Si no selecciona ninguna fila
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto para borrar");
        }

    }//GEN-LAST:event_BorrarButtonActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        vista_principal principal = new vista_principal();
        
        principal.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos_Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarButton;
    private javax.swing.JButton CrearButton;
    private javax.swing.JButton ModificarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaTable;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
